- package-lock.json
- package.json
- src/Components/Admins/AdminForm/AdminForm.jsx
- src/Components/Admins/index.js
- src/Components/Employees/Form/index.js
- src/Components/Employees/List/index.js
- src/Components/Footer/index.js
- src/Components/Header/index.js
- src/Components/Layout/index.js
- src/Components/Projects/Form/index.js
- src/Components/Projects/index.js
- src/Components/SuperAdmins/Form/index.js
- src/Components/SuperAdmins/List/index.js
- src/Components/Tasks/Form/index.js
- src/Components/Tasks/index.js
- src/Components/TimeSheets/Form/index.js
- src/Components/TimeSheets/TimeSheet/index.js
- src/Components/TimeSheets/index.js
- src/index.js
> BaSP-TG-49: react router setup

- src/Components/Admins/AdminForm/AdminForm.jsx
- src/Components/Admins/AdminForm/adminForm.module.css
- src/Components/Employees/Form/form.module.css
- src/Components/Employees/Form/index.js
- src/Components/Projects/Form/form.module.css
- src/Components/Projects/Form/index.js
- src/Components/Shared/TextInput/index.js
- src/Components/Shared/TextInput/text-input.module.css
- src/Components/SuperAdmins/Form/form.module.css
- src/Components/SuperAdmins/Form/index.js
- src/Components/Tasks/Form/index.js
- src/Components/TimeSheets/Form/form.module.css
- src/Components/TimeSheets/Form/index.js
- src/Components/TimeSheets/TimeSheet/index.js
I unified date picker and text inputs, because of the continuity of the forms, and because both are inputs with labels. In all the previous codes, we take both as the same class and give them the same properties.
> BaSP-TG-51: Date Picker and text Inputs hared components.

- src/Components/Admins/AdminList/AdminList.jsx
- src/Components/Tasks/index.js
- src/Components/TimeSheets/TimeSheet/index.js
Timesheets page crashes if any field in timsheet rows list is undefinded
Shloud skip the row and render anyway
---
Added condition to the timsheets table row render
> BaSP-TG-54: fix timesheets pages crash

- src/Components/Shared/Button/button.module.css
- src/Components/Shared/Modal/index.js
Added Button component to Modal
> BaSP-TG-58: added Button component to Modal

- src/Components/Admins/index.js
- src/Components/Employees/index.js
- src/Components/Projects/index.js
- src/Components/Shared/Table/index.js
- src/Components/SuperAdmins/index.js
- src/Components/Tasks/index.js
- src/Components/TimeSheets/index.js
Fix table headers on each entity.
> BaSP-TG-60: Fix header table

- package-lock.json
- package.json
- src/index.js
- src/redux/rootReducer.js
- src/redux/store.js
Implementation of redux, redux-thunk, redux-devtools-extension, and creation of store and the folders to each entity.
> TG-61: Redux setup

- src/Components/Shared/Spinner/spinner.js
- src/Components/Shared/Spinner/spinner.module.css
- src/Components/Shared/Table/index.js
Created spinner shared component.
> BaSP-TG-74: added spinner component

- package.json
- src/Components/Projects/Form/index.js
We fix the projects update/create with @visojulian and @jivescovo .
> BaSP-TG-75: BUG-projects-update/create

- src/Components/Projects/Form/form.module.css
- src/Components/Projects/Form/index.js
- src/Components/Shared/Modal/modal.module.css
- src/Components/Shared/Table/table.module.css
- src/Components/TimeSheets/Form/form.module.css
Fix modal overlay position
Fix project table display
Fix remove all forms dark backgrounds
> BaSP-TG-78: fix modal and project styles

- src/Components/TimeSheets/Form/index.js
- src/Components/TimeSheets/index.js
Time sheets doesnt allow you to edit.
Delete methods dont renderize the table when you delete a Time Sheet.
There are problems reading projects ids and employees ids.
> BaSP-TG-97: Bug fix timesheets

- src/Components/Employee/DeleteEmployee/index.js
- src/Components/Employee/EditEmployee/employee.module.css
- src/Components/Employee/EditEmployee/index.js
- src/Components/Employee/EmployeeProfile/index.js
- src/Components/Employee/EmployeeProfile/profile.module.css
- src/Components/Shared/TextInput/index.js
- src/Components/Shared/TextInput/text-input.module.css
- src/Components/Shared/index.js
- src/redux/employees/thunks.js
- src/routes/employees.js
- src/validations/employees.js
Employee functionalities were updated to further develop the app and each role.  Employee profile and edit employee components and routes were added as well as the delete functionality as described on ticket TG-96. Finally, react hook form was implemented for the edit form, following changes made by @camilavaleriarojas @visojulian and @Licamus.
> BaSP-TG-95: edit/delete employee profile

- src/Components/Employee/Projects/index.js
- src/Components/Employee/Projects/projects.module.css
- src/routes/employees.js
It must be accessed with the following url:  http://localhost:3001/employees/projects/:id
available id for testing: 636011ce7e66200415cc7160
6366da0f243aa34732408bda
6372da017763b02c142f03c4
> BaSP-TG-92: List project by employee

- src/Components/Footer/index.js
- src/Components/Header/index.js
- src/Components/Layout/index.js
- src/index.js
- src/routes/admins.js
- src/routes/employees.js
- src/routes/home.js
- src/routes/index.js
- src/routes/superAdmins.js
Update routing structure so that the app renders each role and its routes only. @visojulian @maxidelfino
> BaSP-TG-98: update routing structure

- src/Components/TimeSheets/index.js
add return null, for vercel render.
> BaSP-TG-102: add return null

- src/Components/Admins/AdminForm/index.js
- src/Components/Admins/index.js
- src/Components/Employee/EditEmployee/index.js
- src/Components/Employee/EmployeeProfile/index.js
- src/Components/Employees/Form/index.js
- src/Components/Employees/List/index.js
- src/Components/Employees/index.js
- src/Components/Projects/Form/index.js
- src/Components/Projects/index.js
- src/Components/Shared/Table/index.js
- src/Components/SuperAdmins/Form/index.js
- src/Components/SuperAdmins/index.js
- src/Components/Tasks/index.js
- src/Components/TimeSheets/Form/index.js
- src/Components/TimeSheets/index.js
> BaSP-TG-101: fix absolute routing

- package-lock.json
- package.json
- src/helpers/firebase/index.js
- src/routes/index.js
Install and setup firebase
Subscribe listener to token id changes
> BaSP-TG-111: setup firebase

- src/helpers/firebase/index.js
- src/redux/auth/actions.js
- src/redux/auth/constants.js
- src/redux/auth/reducer.js
- src/redux/auth/thunks.js
Add constants, actions, reducer and thunks for login/logout validations. We can't test this PR yet because not all other functionalities are implemented.
> BaSP-TG-113: Create Redux Module (login/logout)

- src/Components/Employee/EmployeeProfile/index.js
- src/Components/Employee/EmployeeProfile/profile.module.css
Add button to logout employee using thunk function.
> BaSP-TG-117: Add button to logout employee

- src/Components/Auth/SignUp/index.js
The order of input was changed, now they read from left to right.
> BaSP-TG-103: Reorganise inputs in sign up component

- src/Components/Employee/EmployeeProfile/index.js
Fix modal messgae when user is deleting account
> BaSP-TG-104: fix modal message

- package.json
- src/Components/Admins/index.js
- src/Components/Auth/Login/index.js
- src/Components/Auth/SignUp/index.js
- src/Components/Employee/EditEmployee/index.js
- src/Components/Employee/EmployeeProfile/index.js
- src/Components/Employee/Projects/index.js
- src/Components/Employee/Timesheets/index.js
- src/redux/admins/thunks.js
- src/redux/auth/actions.js
- src/redux/auth/reducer.js
- src/redux/auth/thunks.js
- src/redux/employees/thunks.js
- src/redux/projects/thunks.js
- src/redux/rootReducer.js
- src/redux/superAdmins/thunks.js
- src/redux/task/thunks.js
- src/redux/timeSheets/thunks.js
- src/redux/user/actions.js
- src/redux/user/constants.js
- src/redux/user/reducer.js
- src/redux/user/thunks.js
- src/routes/PrivateRoute.js
- src/routes/employees.js
- src/routes/index.js
Fixed app login
Added redux for /user fetch
Get the user id from state, not from params
Load user data
Fix routing names
Fix routes list 
Delete repeated routes
> BaSP-TG-119: fix app login

- src/Components/Employee/EmployeeProfile/index.js
> BaSP-TG-119: delete repeated get user call

- src/Components/Auth/Login/index.js
Add modal for show the auth error and no redirect when error is true
> BaSP-TG-123: hide auth error

- src/validations/employees.js
- src/validations/projects.js
I added Trim validations from JOI, to avoid empty spaces at the start and the end of the form.
> BaSP-TG-132: Creation of new trim validations

- src/Components/Admins/AdminProfile/index.js
- src/Components/Admins/AdminProfile/profile.module.css
- src/Components/Employee/EditEmployee/index.js
- src/Components/Employee/EmployeeProfile/index.js
- src/Components/Employees/index.js
- src/Components/Projects/index.js
- src/Components/Tasks/index.js
- src/redux/employees/thunks.js
- src/redux/projects/thunks.js
- src/redux/task/thunks.js
- src/routes/admins.js
The admin routes were modified to be able to render Employees, Projects and Tasks. The Admin Profile was also created to show the information in Home section.
> BaSP-TG-128: Correct functioning of Admins

- src/Components/Admins/TimeSheets/index.js
- src/Components/Admins/TimeSheets/list.module.css
- src/Components/Employees/index.js
- src/routes/admins.js
Admin role is now able to see timesheets. Add employee functionality was removed.
> BaSP-TG-128: timesheets on admin rol

- src/Components/Employee/Projects/Form/index.js
- src/Components/Employee/Projects/index.js
- src/routes/employees.js
EMPLOYEE (PM)
Edit project info
Add hours
Visualize project's timesheets
> BaSP-TG-126: EMPLOYEE PM

- src/Components/Employee/Projects/Form/employeeForm.js
- src/Components/Employee/Projects/Form/index.js
- src/Components/Employee/Projects/projects.module.css
- src/Components/Projects/Form/employeeForm.js
- src/Components/Projects/Form/index.js
- src/Components/Projects/projects.module.css
- src/validations/projectEmployees.js
- src/validations/projects.js
Now can submit edit project with "new employee" fields empty
Also can edit project employees list
> BaSP-TG-133: fix submit empty new employee field

- src/routes/admins.js
- src/routes/employees.js
- src/routes/superAdmins.js
When the user is logged, the first thing rendered is now the core function of the role. There's a new route to the profile.
> BaSP-TG-150: Update Navbar Links

- src/Components/Employees/Form/index.js
While editing an employee the password input is no longer shown.
> BaSP-TG-139: Remove employee password input on admins

- src/routes/admins.js
- src/routes/employees.js
- src/routes/superAdmins.js
Error on the routes of each entity was fixed.
> BaSP-TG-162: fix error on routes

- src/Components/Admins/AdminForm/adminForm.module.css
- src/Components/Admins/AdminForm/index.js
- src/Components/Admins/index.js
- src/Components/Auth/Login/index.js
- src/Components/Auth/Login/login.module.css
- src/Components/Auth/SignUp/index.js
- src/Components/Auth/SignUp/sign-up.module.css
- src/Components/Employees/Form/form.module.css
- src/Components/Employees/Form/index.js
- src/Components/Projects/Form/employeeForm.js
- src/Components/Projects/Form/form.module.css
- src/Components/Projects/index.js
- src/Components/Projects/projects.module.css
- src/Components/Shared/Button/button.module.css
- src/Components/Shared/ButtonAdd/buttons.module.css
- src/Components/Shared/ButtonAdd/index.js
- src/Components/Shared/Modal/index.js
- src/Components/Shared/Modal/modal.module.css
- src/Components/Shared/index.js
- src/Components/SuperAdmins/EditSuperAdmin/index.js
- src/Components/SuperAdmins/Form/form.module.css
- src/Components/SuperAdmins/Form/index.js
- src/Components/SuperAdmins/SuperAdminProfile/superAdminProfile.module.css
- src/Components/SuperAdmins/index.js
- src/Components/Tasks/Form/index.js
- src/Components/Tasks/index.js
- src/Components/Tasks/tasks.module.css
New button shared component was created and implemented. The styles of the other button shared component was updated to match Figma styles.
> BaSP-TG-159: Update buttons

- src/validations/employees.js
Name and last name was fixed, now allow compound names.
> BaSP-TG-165: Fix name and last name validations

- src/Components/Employee/EditEmployee/index.js
- src/Components/Employee/EmployeeProfile/index.js
- src/Components/Employees/Form/index.js
- src/Components/Shared/Modal/index.js
- src/routes/employees.js
- src/validations/employees.js
Fix error in phone field at Employee/Profile/Form
> BaSP-TG-151: fix employee form

- src/Components/Auth/Login/index.js
- src/redux/admins/thunks.js
Re-open modal when login error keep ocurring 
Fix styles
> BaSP-TG-158: fix modal bug when login

- src/Components/Home/home.module.css
- src/Components/Home/index.js
Lorem ipsum dummy texts were updated to a real description of the app.
> BaSP-TG-169: change dummy text

- src/Components/Header/header.module.css
- src/Components/Header/index.js
- src/Components/Layout/index.js
- src/routes/admins.js
- src/routes/auth.js
- src/routes/employees.js
- src/routes/home.js
- src/routes/superAdmins.js
A link to home landing page was added to the navbar, the trackgenix icon and to the logout button.
> BaSP-TG-166: links to landing

- src/Components/Employee/Projects/index.js
- src/Components/Employee/Projects/projects.module.css
- src/Components/Shared/Table/index.js
- src/Components/Shared/Table/table.module.css
- src/Components/Shared/index.js
Conditional style and action in delete button inside project table
Only can delete if user is PM or any admin role
> BaSP-TG-172: project delete button

- src/Components/Auth/Login/index.js
- src/Components/Auth/Login/login.module.css
- src/Components/Auth/SignUp/sign-up.module.css
- src/routes/auth.js
Responsive design on the login and sign up forms were implemented.
> BaSP-TG-174: responsive design login / sign up

- src/Components/Employee/Projects/index.js
- src/Components/Employee/Timesheets/index.js
- src/Components/Shared/ButtonAdd/buttons.module.css
- src/routes/auth.js
The colors on the buttons are now consistent throughout the app.
> BaSP-TG-177: correct buttons

- src/Components/Employee/EmployeeProfile/index.js
- src/Components/SuperAdmins/SuperAdminProfile/index.js
Logout thunk was added after deleting an employee or superadmin profile.
> BaSP-TG-186: logout after deleting user

- src/validations/admins.js
- src/validations/employees.js
- src/validations/super-admins.js
The inputs name and last name on Admin, Employee and Super Admin accept compounds names.
> BaSP-TG-181: Compounds names validations

- src/Components/Admins/AdminProfile/profile.module.css
- src/Components/Admins/admins.module.css
- src/Components/Admins/index.js
- src/Components/Employee/EditEmployee/employee.module.css
- src/Components/Employee/EmployeeProfile/profile.module.css
- src/Components/Employee/Projects/Form/form.module.css
- src/Components/Employee/Projects/Form/index.js
- src/Components/Employee/Timesheets/list.module.css
- src/Components/Projects/Form/employeeForm.js
- src/Components/Projects/Form/index.js
- src/Components/Projects/index.js
- src/Components/Projects/projects.module.css
- src/Components/SuperAdmins/SuperAdminProfile/index.js
- src/Components/SuperAdmins/SuperAdminProfile/superAdminProfile.module.css
- src/Components/SuperAdmins/index.js
- src/Components/SuperAdmins/super-admins.module.css
- src/Components/Tasks/index.js
- src/Components/Tasks/tasks.module.css
- src/Components/TimeSheets/Form/form.module.css
The form to edit a project now has the inputs organized and styles were implemented. Minor style changes were made.
> BaSP-TG-180: Fix form edit project

- src/Components/TimeSheets/Form/index.js
Since only the current user can track his own hours, it shouldn´t be able to add timesheets with other employee user
> BaSP-TG-179: fix repeated employee names in select

- src/Components/Employee/Timesheets/index.js
Fix load timesheet list after delete
> BaSP-TG-184: fix load list after delete

- src/Components/Admins/AdminForm/adminForm.module.css
- src/Components/Admins/TimeSheets/index.js
- src/redux/auth/thunks.js
Fix Date length in timesheets list
> BaSP-TG-189: fix timesheets date length

- src/Components/Employee/Timesheets/index.js
> TG-190: fix button in timesheets
